<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\record\CountryBirths;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       
        $countries = array(
            array('c_name' => 'ALBANIA','s_key' => '355'),
            array('c_name' => 'AFGHANISTAN','s_key' => '93'),
            array('c_name' => 'ALGERIA','s_key' => '213'),
            array('c_name' => 'AMERICAN SAMOA','s_key' => '1684'),
            array('c_name' => 'ANDORRA','s_key' => '376'),
            array('c_name' => 'ANGOLA','s_key' => '244'),
            array('c_name' => 'ANGUILLA', 's_key' => '1264'),
            array('c_name' => 'ANTARCTICA', 's_key' => '0'),
            array('c_name' => 'ANTIGUA AND BARBUDA', 's_key' => '1268'),
            array('c_name' => 'ARGENTINA', 's_key' => '54'),
            array('c_name' => 'ARMENIA', 's_key' => '374'),
            array('c_name' => 'ARUBA', 's_key' => '297'),
            array('c_name' => 'AUSTRALIA','s_key' => '61'),
            array('c_name' => 'AUSTRIA', 's_key' => '43'),
            array('c_name' => 'AZERBAIJAN', 's_key' => '994'),
            array('c_name' => 'BAHAMAS', 's_key' => '1242'),
            array('c_name' => 'BAHRAIN', 's_key' => '973'),
            array('c_name' => 'BANGLADESH', 's_key' => '880'),
            array('c_name' => 'BARBADOS', 's_key' => '1246'),
            array('c_name' => 'BELARUS', 's_key' => '375'),
            array('c_name' => 'BELGIUM', 's_key' => '32'),
            array('c_name' => 'BELIZE', 's_key' => '501'),
            array('c_name' => 'BENIN', 's_key' => '229'),
            array('c_name' => 'BERMUDA', 's_key' => '1441'),
            array('c_name' => 'BHUTAN','s_key' => '975'),
            array('c_name' => 'BOLIVIA','s_key' => '591'),
            array('c_name' => 'BOSNIA AND HERZEGOVINA','s_key' => '387'),
            array('c_name' => 'BOTSWANA', 's_key' => '267'),
            array('c_name' => 'BOUVET ISLAND', 's_key' => '0'),
            array('c_name' => 'BRAZIL', 's_key' => '55'),
            array('c_name' => 'BRITISH INDIAN OCEAN TERRITORY', 's_key' => '246'),
            array('c_name' => 'BRUNEI DARUSSALAM', 's_key' => '673'),
            array('c_name' => 'BULGARIA', 's_key' => '359'),
            array('c_name' => 'BURKINA FASO', 's_key' => '226'),
            array('c_name' => 'BURUNDI', 's_key' => '257'),
            array('c_name' => 'CAMBODIA', 's_key' => '855'),
            array('c_name' => 'CAMEROON', 's_key' => '237'),
            array('c_name' => 'CANADA', 's_key' => '1'),
            array('c_name' => 'CAPE VERDE', 's_key' => '238'),
            array('c_name' => 'CAYMAN ISLANDS','s_key' => '1345'),
            array('c_name' => 'CENTRAL AFRICAN REPUBLIC', 's_key' => '236'),
            array('c_name' => 'CHAD','s_key' => '235'),
            array('c_name' => 'CHILE', 's_key' => '56'),
            array('c_name' => 'CHINA','s_key' => '86'),
            array('c_name' => 'CHRISTMAS ISLAND','s_key' => '61'),
            array('c_name' => 'COCOS (KEELING) ISLANDS', 's_key' => '672'),
            array('c_name' => 'COLOMBIA', 's_key' => '57'),
            array('c_name' => 'COMOROS', 's_key' => '269'),
            array('c_name' => 'CONGO', 's_key' => '242'),
            array('c_name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE','s_key' => '242'),
            array('c_name' => 'COOK ISLANDS', 's_key' => '682'),
            array('c_name' => 'COSTA RICA', 's_key' => '506'),
            array('c_name' => 'COTE D\'IVOIRE', 's_key' => '225'),
            array('c_name' => 'CROATIA', 's_key' => '385'),
            array('c_name' => 'CUBA', 's_key' => '53'),
            array('c_name' => 'CYPRUS', 's_key' => '357'),
            array('c_name' => 'CZECH REPUBLIC', 's_key' => '420'),
            array('c_name' => 'DENMARK', 's_key' => '45'),
            array('c_name' => 'DJIBOUTI', 's_key' => '253'),
            array('c_name' => 'DOMINICA', 's_key' => '1767'),
            array('c_name' => 'DOMINICAN REPUBLIC', 's_key' => '1809'),
            array('c_name' => 'ECUADOR', 's_key' => '593'),
            array('c_name' => 'EGYPT', 's_key' => '20'),
            array('c_name' => 'EL SALVADOR','s_key' => '503'),
            array('c_name' => 'EQUATORIAL GUINEA', 's_key' => '240'),
            array('c_name' => 'ERITREA', 's_key' => '291'),
            array('c_name' => 'ESTONIA', 's_key' => '372'),
            array('c_name' => 'ETHIOPIA', 's_key' => '251'),
            array('c_name' => 'FALKLAND ISLANDS (MALVINAS)', 's_key' => '500'),
            array('c_name' => 'FAROE ISLANDS', 's_key' => '298'),
            array('c_name' => 'FIJI','s_key' => '679'),
            array('c_name' => 'FINLAND', 's_key' => '358'),
            array('c_name' => 'FRANCE', 's_key' => '33'),
            array('c_name' => 'FRENCH GUIANA', 's_key' => '594'),
            array('c_name' => 'FRENCH POLYNESIA', 's_key' => '689'),
            array('c_name' => 'FRENCH SOUTHERN TERRITORIES','s_key' => '0'),
            array('c_name' => 'GABON', 's_key' => '241'),
            array('c_name' => 'GAMBIA', 's_key' => '220'),
            array('c_name' => 'GEORGIA', 's_key' => '995'),
            array('c_name' => 'GERMANY', 's_key' => '49'),
            array('c_name' => 'GHANA', 's_key' => '233'),
            array('c_name' => 'GIBRALTAR', 's_key' => '350'),
            array('c_name' => 'GREECE', 's_key' => '30'),
            array('c_name' => 'GREENLAND', 's_key' => '299'),
            array('c_name' => 'GRENADA', 's_key' => '1473'),
            array('c_name' => 'GUADELOUPE', 's_key' => '590'),
            array('c_name' => 'GUAM', 's_key' => '1671'),
            array('c_name' => 'GUATEMALA','s_key' => '502'),
            array('c_name' => 'GUINEA','s_key' => '224'),
            array('c_name' => 'GUINEA-BISSAU','s_key' => '245'),
            array('c_name' => 'GUYANA','s_key' => '592'),
            array('c_name' => 'HAITI', 's_key' => '509'),
            array('c_name' => 'HEARD ISLAND AND MCDONALD ISLANDS','s_key' => '0'),
            array('c_name' => 'HOLY SEE (VATICAN CITY STATE)', 's_key' => '39'),
            array('c_name' => 'HONDURAS','s_key' => '504'),
            array('c_name' => 'HONG KONG', 's_key' => '852'),
            array('c_name' => 'HUNGARY', 's_key' => '36'),
            array('c_name' => 'ICELAND', 's_key' => '354'),
            array('c_name' => 'INDIA','s_key' => '91'),
            array('c_name' => 'INDONESIA', 's_key' => '62'),
            array('c_name' => 'IRAN, ISLAMIC REPUBLIC OF', 's_key' => '98'),
            array('c_name' => 'IRAQ', 's_key' => '964'),
            array('c_name' => 'IRELAND', 's_key' => '353'),
            array('c_name' => 'ISRAEL','s_key' => '972'),
            array('c_name' => 'ITALY', 's_key' => '39'),
            array('c_name' => 'JAMAICA', 's_key' => '1876'),
            array('c_name' => 'JAPAN', 's_key' => '81'),
            array('c_name' => 'JORDAN','s_key' => '962'),
            array('c_name' => 'KAZAKHSTAN', 's_key' => '7'),
            array('c_name' => 'KENYA', 's_key' => '254'),
            array('c_name' => 'KIRIBATI', 's_key' => '686'),
            array('c_name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','s_key' => '850'),
            array('c_name' => 'KOREA, REPUBLIC OF','s_key' => '82'),
            array('c_name' => 'KUWAIT','s_key' => '965'),
            array('c_name' => 'KYRGYZSTAN','s_key' => '996'),
            array('c_name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 's_key' => '856'),
            array('c_name' => 'LATVIA','s_key' => '371'),
            array('c_name' => 'LEBANON', 's_key' => '961'),
            array('c_name' => 'LESOTHO','s_key' => '266'),
            array('c_name' => 'LIBERIA','s_key' => '231'),
            array('c_name' => 'LIBYAN ARAB JAMAHIRIYA', 's_key' => '218'),
            array('c_name' => 'LIECHTENSTEIN','s_key' => '423'),
            array('c_name' => 'LITHUANIA','s_key' => '370'),
            array('c_name' => 'LUXEMBOURG', 's_key' => '352'),
            array('c_name' => 'MACAO', 's_key' => '853'),
            array('c_name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','s_key' => '389'),
            array('c_name' => 'MADAGASCAR', 's_key' => '261'),
            array('c_name' => 'MALAWI','s_key' => '265'),
            array('c_name' => 'MALAYSIA', 's_key' => '60'),
            array('c_name' => 'MALDIVES', 's_key' => '960'),
            array('c_name' => 'MALI', 's_key' => '223'),
            array('c_name' => 'MALTA', 's_key' => '356'),
            array('c_name' => 'MARSHALL ISLANDS', 's_key' => '692'),
            array('c_name' => 'MARTINIQUE','s_key' => '596'),
            array('c_name' => 'MAURITANIA','s_key' => '222'),
            array('c_name' => 'MAURITIUS', 's_key' => '230'),
            array('c_name' => 'MAYOTTE', 's_key' => '269'),
            array('c_name' => 'MEXICO', 's_key' => '52'),
            array('c_name' => 'MICRONESIA, FEDERATED STATES OF', 's_key' => '691'),
            array('c_name' => 'MOLDOVA, REPUBLIC OF', 's_key' => '373'),
            array('c_name' => 'MONACO', 's_key' => '377'),
            array('c_name' => 'MONGOLIA', 's_key' => '976'),
            array('c_name' => 'MONTSERRAT', 's_key' => '1664'),
            array('c_name' => 'MOROCCO', 's_key' => '212'),
            array('c_name' => 'MOZAMBIQUE','s_key' => '258'),
            array('c_name' => 'MYANMAR','s_key' => '95'),
            array('c_name' => 'NAMIBIA', 's_key' => '264'),
            array('c_name' => 'NAURU', 's_key' => '674'),
            array('c_name' => 'NEPAL', 's_key' => '977'),
            array('c_name' => 'NETHERLANDS', 's_key' => '31'),
            array('c_name' => 'NETHERLANDS ANTILLES', 's_key' => '599'),
            array('c_name' => 'NEW CALEDONIA','s_key' => '687'),
            array('c_name' => 'NEW ZEALAND', 's_key' => '64'),
            array('c_name' => 'NICARAGUA', 's_key' => '505'),
            array('c_name' => 'NIGER', 's_key' => '227'),
            array('c_name' => 'NIGERIA', 's_key' => '234'),
            array('c_name' => 'NIUE', 's_key' => '683'),
            array('c_name' => 'NORFOLK ISLAND', 's_key' => '672'),
            array('c_name' => 'NORTHERN MARIANA ISLANDS', 's_key' => '1670'),
            array('c_name' => 'NORWAY','s_key' => '47'),
            array('c_name' => 'OMAN', 's_key' => '968'),
            array('c_name' => 'PAKISTAN', 's_key' => '92'),
            array('c_name' => 'PALAU', 's_key' => '680'),
            array('c_name' => 'PALESTINIAN TERRITORY, OCCUPIED', 's_key' => '970'),
            array('c_name' => 'PANAMA','s_key' => '507'),
            array('c_name' => 'PAPUA NEW GUINEA','s_key' => '675'),
            array('c_name' => 'PARAGUAY', 's_key' => '595'),
            array('c_name' => 'PERU','s_key' => '51'),
            array('c_name' => 'PHILIPPINES', 's_key' => '63'),
            array('c_name' => 'PITCAIRN','s_key' => '0'),
            array('c_name' => 'POLAND', 's_key' => '48'),
            array('c_name' => 'PORTUGAL', 's_key' => '351'),
            array('c_name' => 'PUERTO RICO', 's_key' => '1787'),
            array('c_name' => 'QATAR', 's_key' => '974'),
            array('c_name' => 'REUNION', 's_key' => '262'),
            array('c_name' => 'ROMANIA', 's_key' => '40'),
            array('c_name' => 'RUSSIAN FEDERATION','s_key' => '70'),
            array('c_name' => 'RWANDA','s_key' => '250'),
            array('c_name' => 'SAINT HELENA','s_key' => '290'),
            array('c_name' => 'SAINT KITTS AND NEVIS', 's_key' => '1869'),
            array('c_name' => 'SAINT LUCIA', 's_key' => '1758'),
            array('c_name' => 'SAINT PIERRE AND MIQUELON','s_key' => '508'),
            array('c_name' => 'SAINT VINCENT AND THE GRENADINES', 's_key' => '1784'),
            array('c_name' => 'SAMOA', 's_key' => '684'),
            array('c_name' => 'SAN MARINO', 's_key' => '378'),
            array('c_name' => 'SAO TOME AND PRINCIPE', 's_key' => '239'),
            array('c_name' => 'SAUDI ARABIA', 's_key' => '966'),
            array('c_name' => 'SENEGAL', 's_key' => '221'),
            array('c_name' => 'SERBIA AND MONTENEGRO', 's_key' => '381'),
            array('c_name' => 'SEYCHELLES', 's_key' => '248'),
            array('c_name' => 'SIERRA LEONE', 's_key' => '232'),
            array('c_name' => 'SINGAPORE', 's_key' => '65'),
            array('c_name' => 'SLOVAKIA','s_key' => '421'),
            array('c_name' => 'SLOVENIA', 's_key' => '386'),
            array('c_name' => 'SOLOMON ISLANDS', 's_key' => '677'),
            array('c_name' => 'SOMALIA', 's_key' => '252'),
            array('c_name' => 'SOUTH AFRICA', 's_key' => '27'),
            array('c_name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','s_key' => '0'),
            array('c_name' => 'SPAIN','s_key' => '34'),
            array('c_name' => 'SRI LANKA', 's_key' => '94'),
            array('c_name' => 'SUDAN','s_key' => '249'),
            array('c_name' => 'SURIc_name', 's_key' => '597'),
            array('c_name' => 'SVALBARD AND JAN MAYEN', 's_key' => '47'),
            array('c_name' => 'SWAZILAND', 's_key' => '268'),
            array('c_name' => 'SWEDEN', 's_key' => '46'),
            array('c_name' => 'SWITZERLAND', 's_key' => '41'),
            array('c_name' => 'SYRIAN ARAB REPUBLIC','s_key' => '963'),
            array('c_name' => 'TAIWAN, PROVINCE OF CHINA', 's_key' => '886'),
            array('c_name' => 'TAJIKISTAN','s_key' => '992'),
            array('c_name' => 'TANZANIA, UNITED REPUBLIC OF', 's_key' => '255'),
            array('c_name' => 'THAILAND', 's_key' => '66'),
            array('c_name' => 'TIMOR-LESTE', 's_key' => '670'),
            array('c_name' => 'TOGO', 's_key' => '228'),
            array('c_name' => 'TOKELAU', 's_key' => '690'),
            array('c_name' => 'TONGA', 's_key' => '676'),
            array('c_name' => 'TRINIDAD AND TOBAGO','s_key' => '1868'),
            array('c_name' => 'TUNISIA', 's_key' => '216'),
            array('c_name' => 'TURKEY', 's_key' => '90'),
            array('c_name' => 'TURKMENISTAN', 's_key' => '7370'),
            array('c_name' => 'TURKS AND CAICOS ISLANDS', 's_key' => '1649'),
            array('c_name' => 'TUVALU', 's_key' => '688'),
            array('c_name' => 'UGANDA', 's_key' => '256'),
            array('c_name' => 'UKRAINE', 's_key' => '380'),
            array('c_name' => 'UNITED ARAB EMIRATES', 's_key' => '971'),
            array('c_name' => 'UNITED KINGDOM', 's_key' => '44'),
            array('c_name' => 'UNITED STATES','s_key' => '1'),
            array('c_name' => 'UNITED STATES MINOR OUTLYING ISLANDS', 's_key' => '1'),
            array('c_name' => 'URUGUAY', 's_key' => '598'),
            array('c_name' => 'UZBEKISTAN', 's_key' => '998'),
            array('c_name' => 'VANUATU', 's_key' => '678'),
            array('c_name' => 'VENEZUELA','s_key' => '58'),
            array('c_name' => 'VIET NAM','s_key' => '84'),
            array('c_name' => 'VIRGIN ISLANDS, BRITISH', 's_key' => '1284'),
            array('c_name' => 'VIRGIN ISLANDS, U.S.', 's_key' => '1340'),
            array('c_name' => 'WALLIS AND FUTUNA', 's_key' => '681'),
            array('c_name' => 'WESTERN SAHARA', 's_key' => '212'),
            array('c_name' => 'YEMEN','s_key' => '967'),
            array('c_name' => 'ZAMBIA', 's_key' => '260'),
            array('c_name' => 'ZIMBABWE', 's_key' => '263'),
            array('c_name' => 'SERBIA','s_key' => '381'),
            array('c_name' => 'ASIA PACIFIC REGION','s_key' => '0'),
            array('c_name' => 'MONTENEGRO', 's_key' => '382'),
            array('c_name' => 'ALAND ISLANDS', 's_key' => '358'),
            array('c_name' => 'BONAIRE, SINT EUSTATIUS AND SABA', 's_key' => '599'),
            array('c_name' => 'CURACAO', 's_key' => '599'),
            array('c_name' => 'GUERNSEY','s_key' => '44'),
            array('c_name' => 'ISLE OF MAN','s_key' => '44'),
            array('c_name' => 'JERSEY', 's_key' => '44'),
            array('c_name' => 'KOSOVO','s_key' => '381'),
            array('c_name' => 'SAINT BARTHELEMY', 's_key' => '590'),
            array('c_name' => 'SAINT MARTIN', 's_key' => '590'),
            array('c_name' => 'SINT MAARTEN', 's_key' => '1'),
            array('c_name' => 'SOUTH SUDAN',  's_key' => '211')
          );

          DB::table('country_births')->insert($countries);

    }
}
